"""Stage 4 — load manual.json into Supabase. Idempotent.

    python tools/load.py --check     what would change, touches nothing
    python tools/load.py             upsert nodes then blocks
    python tools/load.py --prune     also delete rows no longer in manual.json
    python tools/load.py --sql       emit build/seed.sql instead of connecting

Needs a service role key — the anon key cannot write past RLS:

    export SUPABASE_SERVICE_ROLE_KEY=...      # Supabase dashboard > Settings > API
    # or put it in .env as SUPABASE_SERVICE_ROLE_KEY (it is gitignored)

The project URL is read from .env (VITE_SUPABASE_URL) unless SUPABASE_URL is set.

Idempotency: block ids are sha1(lang|node_key|ordinal)[:8] and node keys are the
paragraph numbers, so re-running upserts onto the same rows. Two consecutive builds
of manual.json are byte-identical, so a re-load is a no-op. That is the property the
translation work depends on — ids must never churn, or every alignment breaks.
"""
import json, os, re, sys, argparse, pathlib, itertools
import requests

sys.stdout.reconfigure(encoding='utf-8')
ROOT = pathlib.Path(__file__).resolve().parent.parent
BATCH = 500

NODE_COLS = ('key', 'role', 'number', 'number_visible', 'sort_key',
             'parent_key', 'section_key', 'level', 'doc_order')
BLOCK_COLS = ('id', 'node_key', 'lang', 'ordinal', 'kind', 'marker',
              'body', 'source_line', 'is_lead')


def env(name):
    """Read from the environment, falling back to .env (which may be UTF-16)."""
    if os.environ.get(name):
        return os.environ[name]
    p = ROOT / '.env'
    if not p.exists():
        return None
    raw = p.read_bytes()
    for enc in ('utf-16', 'utf-8-sig', 'utf-8'):
        try:
            text = raw.decode(enc)
            break
        except UnicodeError:
            continue
    else:
        return None
    text = text.replace('\x00', '')
    m = re.search(r'^\s*%s\s*=\s*(\S+)' % re.escape(name), text, re.M)
    return m.group(1).strip('"\'') if m else None


def load_file():
    M = json.load(open(ROOT / 'manual.json', encoding='utf8'))
    nodes = [{'key': d['key'], 'role': d['role'], 'number': d['number'],
              'number_visible': d['number_visible'], 'sort_key': d['sort_key'],
              'parent_key': d['parent_key'], 'section_key': d['section_key'],
              'level': d['level'], 'doc_order': d['order']}
             for d in M['nodes']]
    blocks = [{k: b[k] for k in BLOCK_COLS} for b in M['blocks']]
    return M, nodes, blocks


def chunks(rows, n=BATCH):
    it = iter(rows)
    while True:
        c = list(itertools.islice(it, n))
        if not c:
            return
        yield c


# ------------------------------------------------------------------ SQL mode
def sqlite_quote(v):
    if v is None:
        return 'null'
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, int):
        return str(v)
    if isinstance(v, list):
        return "'{%s}'" % ','.join(str(x) for x in v)
    return "'" + str(v).replace("'", "''") + "'"


def emit_sql(nodes, blocks):
    out = [ '-- Generated by tools/load.py --sql. Safe to re-run.',
            'begin;',
            'set constraints all deferred;' ]
    for table, cols, rows in (('nodes', NODE_COLS, nodes), ('blocks', BLOCK_COLS, blocks)):
        pk = 'key' if table == 'nodes' else 'id'
        upd = ', '.join('%s = excluded.%s' % (c, c) for c in cols if c != pk)
        for batch in chunks(rows, 200):
            vals = ',\n  '.join('(%s)' % ', '.join(sqlite_quote(r[c]) for c in cols)
                                for r in batch)
            out.append('insert into public.%s (%s) values\n  %s\non conflict (%s) do update set %s;'
                       % (table, ', '.join(cols), vals, pk, upd))
    out.append('commit;')
    path = ROOT / 'build/seed.sql'
    path.write_text('\n'.join(out), encoding='utf8')
    print('wrote %s — %d nodes, %d blocks, %.1f MB'
          % (path, len(nodes), len(blocks), path.stat().st_size / 1e6))
    print('Run it in the Supabase SQL editor, or:')
    print('  psql "$DATABASE_URL" -f build/seed.sql')


# ------------------------------------------------------------------ REST mode
class Api:
    def __init__(self, url, key):
        self.base = url.rstrip('/') + '/rest/v1'
        self.s = requests.Session()
        self.s.headers.update({'apikey': key, 'Authorization': 'Bearer ' + key,
                               'Content-Type': 'application/json'})

    def upsert(self, table, rows, on_conflict):
        for batch in chunks(rows):
            r = self.s.post('%s/%s' % (self.base, table),
                            params={'on_conflict': on_conflict},
                            headers={'Prefer': 'resolution=merge-duplicates,return=minimal'},
                            data=json.dumps(batch))
            if r.status_code >= 300:
                sys.exit('%s upsert failed (%d): %s' % (table, r.status_code, r.text[:600]))
            print('  %s +%d' % (table, len(batch)))

    def keys(self, table, col):
        got, offset = [], 0
        while True:
            r = self.s.get('%s/%s' % (self.base, table),
                           params={'select': col, 'limit': 1000, 'offset': offset})
            if r.status_code >= 300:
                sys.exit('%s read failed (%d): %s' % (table, r.status_code, r.text[:400]))
            page = r.json()
            got += [x[col] for x in page]
            if len(page) < 1000:
                return got
            offset += 1000

    def delete_in(self, table, col, values):
        for batch in chunks(values, 200):
            quoted = ','.join('"%s"' % v.replace('"', '\\"') for v in batch)
            r = self.s.delete('%s/%s' % (self.base, table),
                              params={col: 'in.(%s)' % quoted},
                              headers={'Prefer': 'return=minimal'})
            if r.status_code >= 300:
                sys.exit('%s delete failed (%d): %s' % (table, r.status_code, r.text[:400]))
            print('  %s -%d' % (table, len(batch)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='report differences, write nothing')
    ap.add_argument('--prune', action='store_true', help='delete rows absent from manual.json')
    ap.add_argument('--sql', action='store_true', help='emit build/seed.sql instead')
    a = ap.parse_args()

    M, nodes, blocks = load_file()
    print('manual.json: %d nodes, %d blocks, lang=%s' % (len(nodes), len(blocks), M['lang']))

    if a.sql:
        return emit_sql(nodes, blocks)

    url = env('SUPABASE_URL') or env('VITE_SUPABASE_URL')
    key = env('SUPABASE_SERVICE_ROLE_KEY')
    if not url:
        sys.exit('No project URL. Set SUPABASE_URL or VITE_SUPABASE_URL.')
    if not key:
        sys.exit('No SUPABASE_SERVICE_ROLE_KEY. The anon key cannot write past RLS.\n'
                 'Get one from the Supabase dashboard > Settings > API, or use --sql.')
    print('target: %s' % url)
    api = Api(url, key)

    have_nodes = set(api.keys('nodes', 'key'))
    have_blocks = set(api.keys('blocks', 'id'))
    want_nodes = {d['key'] for d in nodes}
    want_blocks = {b['id'] for b in blocks}

    print('remote : %d nodes, %d blocks' % (len(have_nodes), len(have_blocks)))
    print('new    : %d nodes, %d blocks' % (len(want_nodes - have_nodes),
                                            len(want_blocks - have_blocks)))
    print('stale  : %d nodes, %d blocks' % (len(have_nodes - want_nodes),
                                            len(have_blocks - want_blocks)))
    if a.check:
        for label, s in (('stale nodes', have_nodes - want_nodes),
                         ('stale blocks', have_blocks - want_blocks)):
            if s:
                print('  %s: %s%s' % (label, sorted(s)[:10], ' ...' if len(s) > 10 else ''))
        return print('--check: nothing written.')

    # Blocks first when pruning: they cascade from nodes, and deleting a node whose
    # blocks are still wanted would take them with it.
    if a.prune:
        if have_blocks - want_blocks:
            api.delete_in('blocks', 'id', sorted(have_blocks - want_blocks))
        if have_nodes - want_nodes:
            api.delete_in('nodes', 'key', sorted(have_nodes - want_nodes))
    elif (have_nodes - want_nodes) or (have_blocks - want_blocks):
        print('note: stale rows left in place. Re-run with --prune to remove them.')

    api.upsert('nodes', nodes, 'key')
    api.upsert('blocks', blocks, 'id')

    n = len(api.keys('nodes', 'key'))
    b = len(api.keys('blocks', 'id'))
    print('after  : %d nodes, %d blocks' % (n, b))
    if a.prune:
        assert n == len(nodes) and b == len(blocks), 'row counts do not match manual.json'
        print('counts match manual.json exactly')


if __name__ == '__main__':
    main()
